name: sdk-test-testdatagen
author: hpoeche

description: Fetches generated example files from the aas-specs-metamodel repository and tries to deserialize them

inputs:
  AAS_SPECS_RELEASE_TAG:
    required: true
    description: A tag on the aas-specs-metamodel repository which defines the version of metamodel to test

runs:
  using: 'composite'
  steps:
    - name: Checkout aas-specs-metamodel repository
      uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 #v5.1.0
      with:
        repository: 'admin-shell-io/aas-specs-metamodel'
        ref: ${{ inputs.AAS_SPECS_RELEASE_TAG }}
        path: 'aas-specs-metamodel'

    - name: Run tests on example files
      shell: bash
      run: |
        python etc/sdk-testdatagen/deserialization_tests.py \
          --examples aas-specs-metamodel/schemas \
          --output sdk-testdatagen-output \
          --summary $GITHUB_STEP_SUMMARY

    - name: Upload test output
      if: ${{ always() }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        path: sdk-testdatagen-output
        name: sdk_testdatagen_results