name: basyx-python-server
services:
  app:
    build:
      context: ../..
      additional_contexts:
        - sdk=../../../sdk
      dockerfile: ./docker/discovery/Dockerfile
    ports:
    - "8084:80"
    environment:
      storage_path: /storage/discovery_store.json
    volumes:
      - ./storage:/storage
