name: main
on:
  pull_request:
     branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  X_API_VERSION: "v3.1"
  X_PYTHON_MIN_VERSION: "3.10"
  X_AAS_SPECS_RELEASE_TAG: "v3.1.2"

jobs:
  server-docker-arm:
    # This job checks if we can build our server package
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        profile: [ "repository", "discovery", "registry" ]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 #v5.1.0

      - uses: ./.github/actions/build-server
        id: build
        with:
          server-profile: ${{ matrix.profile }}
          load: true
          publish: false
          platform: linux/arm64
      - name: Run container
        run: |
          docker run -d --name basyx-python-${{ matrix.profile }} -p 9080:80 --pull=never ${{ steps.build.outputs.image-ref }}
      - name: Wait for container and server initialization
        run: |
          timeout 30s bash -c '
            until docker logs basyx-python-${{ matrix.profile }} 2>&1 | grep -q "INFO success: quit_on_failure entered RUNNING state"; do
              sleep 2
            done
          '
      - name: Check if service is alive
        run: |
          curl -f http://localhost:9080/api/${{ env.X_API_VERSION }}/description
      - name: Stop and remove the container
        run: |
          docker stop basyx-python-${{ matrix.profile }} && docker rm basyx-python-${{ matrix.profile }}

  sdk-testdatagen:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 #v5.1.0
     - name: Set up Python
       uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v7
       with:
         python-version: ${{ env.X_PYTHON_MIN_VERSION }}
         cache: "pip"
         cache-dependency-path: "**/pyproject.toml"
     - name: Install Python dependencies
       working-directory: ./sdk
       run: |
         python -m pip install --upgrade pip
         python -m pip install .[dev]
     - uses: ./.github/actions/sdk-test-testdatagen
       with:
         AAS_SPECS_RELEASE_TAG: ${{ env.X_AAS_SPECS_RELEASE_TAG }}
